// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmacsqjdknfpfxzmwjrk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhtYWNzcWpka25mcGZ4em13anJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3Mzc4ODksImV4cCI6MjA2MzMxMzg4OX0.ExHB0UemoQU0x7eOIdEMyzL5JNDfot6gR4zQZocW_E8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);